# Generated by Django 2.2.7 on 2019-11-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_roommessage_sender_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommessage',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
