# Generated by Django 2.2.7 on 2019-11-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keywords',
            old_name='sender_id',
            new_name='name',
        ),
    ]
