# Generated by Django 2.2.7 on 2019-11-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191106_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='alias',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
