# Generated by Django 2.2.7 on 2019-11-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_room_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='alias',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
