# Generated by Django 2.2.7 on 2019-11-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20191107_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
